## DataFrame 创建方式

In [1]:
# dataframe的创建方式
import pandas as pd
import numpy as np
# 通过Series来创建
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
df = pd.DataFrame({"第1列":s1,"第2列":s2})
print(type(df))
print(type(df["第1列"]))
# 通过字典来创建
'''
dataframe的每一列都是一个Series对象，字典的key就是列名，value就是数据
columns参数可以指定列的顺序，index参数可以指定行索引
'''
df = pd.DataFrame({
    "姓名":["张三","李四","王五"],
    "年龄":[18,19,20],
    "性别":["男","女","男"],
    "成绩":[90,95,85]
},index=[1,2,3],columns=["姓名","年龄","成绩","性别"]
)
df

<class 'pandas.DataFrame'>
<class 'pandas.Series'>

   姓名  年龄  成绩 性别
1  张三  18  90  男
2  李四  19  95  女
3  王五  20  85  男

In [2]:
# dataframe的属性
print('行索引：',df.index)
print('列标签：',df.columns)
print('值：',df.values)
print('维度：',df.ndim)
print('形状：',df.shape)
print('元素个数：',df.size)
print('\n数据类型：\n',df.dtypes)

行索引： Index([1, 2, 3], dtype='int64')
列标签： Index(['姓名', '年龄', '成绩', '性别'], dtype='str')
值： [['张三' 18 90 '男']
 ['李四' 19 95 '女']
 ['王五' 20 85 '男']]
维度： 2
形状： (3, 4)
元素个数： 12

数据类型：
 姓名      str
年龄    int64
成绩    int64
性别      str
dtype: object

In [3]:
print('行列转置：\n',df.T)
print(df.T.index)
print(df.T.columns)

行列转置：
      1   2   3
姓名  张三  李四  王五
年龄  18  19  20
成绩  90  95  85
性别   男   女   男
Index(['姓名', '年龄', '成绩', '性别'], dtype='str')
Index([1, 2, 3], dtype='int64')

In [4]:
# 获取元素 loc iloc at iat
# 获取某行数据
print(df)
print(df.loc[1])    # 显式索引
print(df.iloc[0])   # 隐式索引

   姓名  年龄  成绩 性别
1  张三  18  90  男
2  李四  19  95  女
3  王五  20  85  男
姓名    张三
年龄    18
成绩    90
性别     男
Name: 1, dtype: object
姓名    张三
年龄    18
成绩    90
性别     男
Name: 1, dtype: object

In [5]:
# 获取某列数据
print(df)
print(df.loc[:,"姓名"])    # 显式索引
print(df.iloc[:,0])       # 隐式索引
print(df["姓名"])          # 直接通过列名获取   最常用
print(df.姓名)            # 直接通过属性获取

   姓名  年龄  成绩 性别
1  张三  18  90  男
2  李四  19  95  女
3  王五  20  85  男
1    张三
2    李四
3    王五
Name: 姓名, dtype: str
1    张三
2    李四
3    王五
Name: 姓名, dtype: str
1    张三
2    李四
3    王五
Name: 姓名, dtype: str
1    张三
2    李四
3    王五
Name: 姓名, dtype: str

In [6]:
# 单个元素，at和loc获取单个元素其实差不多，只是at的速度更快一些
print(df.at[1,"姓名"])    # 显式索引，应该获取到张三
print(df.iat[0,0])       # 隐式索引，应该获取到张三
print(df.loc[1,"姓名"])    # 显式索引，应该获取到张三
print(df.iloc[0,0])       # 隐式索引，应该获取到张三

张三
张三
张三
张三

In [7]:
# 获取单列数据
print(df["成绩"])
print(df.成绩)

1    90
2    95
3    85
Name: 成绩, dtype: int64
1    90
2    95
3    85
Name: 成绩, dtype: int64

In [8]:
# 查看部分数据
print(df.head(2))  # 查看前两行数据
print(df.tail(2))  # 查看后两行数据

   姓名  年龄  成绩 性别
1  张三  18  90  男
2  李四  19  95  女
   姓名  年龄  成绩 性别
2  李四  19  95  女
3  王五  20  85  男

In [9]:
# 布尔索引
# 找出score > 85的
print(df[df.成绩 > 85])
# 找出score > 85 并且 年龄<19的
print(df[(df.成绩 > 85) & (df.年龄 < 19)])

   姓名  年龄  成绩 性别
1  张三  18  90  男
2  李四  19  95  女
   姓名  年龄  成绩 性别
1  张三  18  90  男

In [10]:
# 随机抽样，默认取1条，取多条写参数
df.sample()

   姓名  年龄  成绩 性别
2  李四  19  95  女

In [11]:
# 查看元素是否包含在参数集合中
print(df.isin(['张三',19]))

      姓名     年龄     成绩     性别
1   True  False  False  False
2  False   True  False  False
3  False  False  False  False

In [12]:
 # 查看是否是缺失值
 print(df.isna())

      姓名     年龄     成绩     性别
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False

In [13]:
print(df["成绩"].sum())
print(df["成绩"].mean())
print(df["成绩"].max())
print(df["成绩"].min())
print(df["成绩"].median())
print(df["性别"].mode())

270
90.0
95
85
90.0
0    男
Name: 性别, dtype: str

In [14]:
print(df.count())   # 每一列非缺失值的数量

姓名    3
年龄    3
成绩    3
性别    3
dtype: int64

In [15]:
print(df.value_counts())   # 每一列数据出现的次数

姓名  年龄  成绩  性别
张三  18  90  男     1
李四  19  95  女     1
王五  20  85  男     1
Name: count, dtype: int64

In [16]:
print(df.drop_duplicates())   # 删除重复数据

   姓名  年龄  成绩 性别
1  张三  18  90  男
2  李四  19  95  女
3  王五  20  85  男

In [17]:
print(df.duplicated())   # 检查是否为重复数据，返回布尔值

1    False
2    False
3    False
dtype: bool

In [18]:
print(df.replace(90,100))   # 替换数据

   姓名  年龄   成绩 性别
1  张三  18  100  男
2  李四  19   95  女
3  王五  20   85  男

In [19]:
df

   姓名  年龄  成绩 性别
1  张三  18  90  男
2  李四  19  95  女
3  王五  20  85  男

In [20]:
df.cumsum()   # 计算累计和
print(df.cumsum())
df.cummin()   # 计算累计最小值

       姓名  年龄   成绩   性别
1      张三  18   90    男
2    张三李四  37  185   男女
3  张三李四王五  57  270  男女男

   姓名  年龄  成绩 性别
1  张三  18  90  男
2  张三  18  90  女
3  张三  18  85  女

In [21]:
print(df.sort_index(ascending=False))   # 按照索引排序
print(df.sort_values(by='成绩',ascending=False))   # 参数：by='按什么进行排序'
# 多值排序可以 参数：by=['按什么进行排序']
print(df.sort_values(by=['成绩','年龄'],ascending=[False,True]))   # 参数：by=['按什么进行排序'],ascending=[是否是否升序]

   姓名  年龄  成绩 性别
3  王五  20  85  男
2  李四  19  95  女
1  张三  18  90  男
   姓名  年龄  成绩 性别
2  李四  19  95  女
1  张三  18  90  男
3  王五  20  85  男
   姓名  年龄  成绩 性别
2  李四  19  95  女
1  张三  18  90  男
3  王五  20  85  男

In [22]:
'''
案例 1：学生成绩分析
场景：某班级的学生成绩数据如下，请完成以下任务：
1．计算每位学生的总分和平均分。
2．找出数学成绩高于 90 分或英语成绩高于 85 分的学生。
3．按总分从高到低排序，并输出前 3 名学生。
'''
import pandas as pd
data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}

In [23]:
scores = pd.DataFrame(data)
# 1．计算每位学生的总分和平均分。
scores['总分'] = scores[['数学', '英语', '物理']].sum(axis=1)
scores['平均分'] = scores[['数学', '英语', '物理']].mean(axis=1).round(1)  # 保留1位小数
# 2．找出数学成绩高于 90 分或英语成绩高于 85 分的学生。
print(scores[(scores['数学'] > 90) | (scores['英语'] > 85)])
# 3．按总分从高到低排序，并输出前 3 名学生。
print(scores.sort_values(by='总分', ascending=False).head(3))

   姓名  数学  英语  物理   总分   平均分
0  张三  85  90  75  250  83.3
1  李四  92  88  80  260  86.7
3  赵六  88  92  85  265  88.3
4  钱七  95  80  90  265  88.3
   姓名  数学  英语  物理   总分   平均分
4  钱七  95  80  90  265  88.3
3  赵六  88  92  85  265  88.3
1  李四  92  88  80  260  86.7

In [24]:
'''
案例 2：销售数据分析
场景：某公司销售数据如下，请完成以下任务：
1．计算每种产品的总销售额（销售额 = 单价 × 销量）。
2．找出销售额最高的产品。
3．按销售额从高到低排序，并输出所有产品信息。
'''
import pandas as pd
data = {
    '产品名称': ['A', 'B', 'C', 'D'],
    '单价': [100, 150, 200, 120],
    '销量': [50, 30, 20, 40]
}
df = pd.DataFrame(data)

In [25]:
# 1．计算每种产品的总销售额（销售额 = 单价 × 销量）。
df['销售额'] = df['单价'] * df['销量']
df
# 2．找出销售额最高的产品。
print(df.nlargest(1, columns=['销售额']))
# 3．按销售额从高到低排序，并输出所有产品信息。
df.sort_values(by='销售额', ascending=False)

  产品名称   单价  销量   销售额
0    A  100  50  5000

  产品名称   单价  销量   销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000

In [26]:
'''
案例 3：电商用户行为分析
场景：某电商平台的用户行为数据如下，请完成以下任务：
1．计算每位用户的总消费金额（消费金额 = 商品单价 × 购买数量）
2．找出消费金额最高的用户，并输出其所有信息
3．计算所有用户的平均消费金额（保留 2 位小数）
4．统计电子产品的总购买数量
'''
import pandas as pd

data = {
    '用户ID': [101, 102, 103, 104, 105],
    '用户名': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    '商品类别': ['电子产品', '服饰', '电子产品', '家居', '服饰'],
    '商品单价': [1200, 300, 800, 150, 200],
    '购买数量': [1, 3, 2, 5, 4]
}
df = pd.DataFrame (data)
df

   用户ID      用户名  商品类别  商品单价  购买数量
0   101    Alice  电子产品  1200     1
1   102      Bob    服饰   300     3
2   103  Charlie  电子产品   800     2
3   104    David    家居   150     5
4   105      Eve    服饰   200     4

In [27]:
# 1．计算每位用户的总消费金额（消费金额 = 商品单价 × 购买数量）
df['总消费金额'] = df['商品单价'] * df['购买数量']
df
# 2．找出消费金额最高的用户，并输出其所有信息
print(df.nlargest(1, columns=['总消费金额']))
# 3．计算所有用户的平均消费金额（保留 2 位小数）
print(df['总消费金额'].mean().round(2))
# 4．统计电子产品的总购买数量
print(df[df['商品类别'] == '电子产品']['购买数量'].sum())

   用户ID      用户名  商品类别  商品单价  购买数量  总消费金额
2   103  Charlie  电子产品   800     2   1600
1050.0
3